server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: aura
    password: aura
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    stream:
      bindings:
        otpRequestedOut-out-0:
          destination: ${aura.kafka.topics.otp-requested}

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.aura: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info

aura:
  auth:
    otp:
      message-template: "کد ورود شما: %s"
      ttl-minutes: 3
      otp-binding-name: "otpRequestedOut-out-0"
    jwt:
      secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration-ms: 86400000
  kafka:
    topics:
      otp-requested: ${KAFKA_TOPIC_OTP_REQUESTED:otp-requested-topic}