package com.aura.common.web.observation;

import io.micrometer.observation.Observation;
import io.micrometer.observation.ObservationPredicate;
import org.springframework.http.server.observation.ServerRequestObservationContext;

/**
 * Keeps the monitoring out of the traces.
 *
 * <p>Prometheus scrapes every service every fifteen seconds, and each scrape is an HTTP request
 * that Micrometer will happily turn into a trace. Eight services makes roughly thirty traces a
 * minute, forever, none of which anyone will ever open — and they are indistinguishable at a
 * glance from the ones that matter, so finding a real checkout means scrolling past them.
 *
 * <p>Health probes are the same story: Docker checks readiness every ten seconds.
 *
 * <p>Note this suppresses the observation entirely, which also drops the metric. That is the right
 * trade here: {@code /actuator} traffic is generated by the monitoring itself, so timing it tells
 * you about Prometheus rather than about the shop.
 */
public class ActuatorObservationPredicate implements ObservationPredicate {

    @Override
    public boolean test(String name, Observation.Context context) {
        if (!(context instanceof ServerRequestObservationContext serverContext)) {
            return true;
        }
        String path = serverContext.getCarrier().getRequestURI();
        return path == null || !path.startsWith("/actuator");
    }
}
